version: '3.7'
services:
  bamboo:
    build: .
    image: ragedunicorn/bamboo:${BAMBOO_TAG_VERSION}-dev
    volumes:
      - bamboo_data:/var/atlassian/bamboo
      - bamboo_logs:/opt/atlassian/bamboo/logs
    environment:
      POSTGRESQL_APP_USER: "app"
      POSTGRESQL_APP_PASSWORD: "app"
      POSTGRESQL_DATABASE_HOSTNAME: "postgresql"
      BAMBOO_DATABASE_NAME: "bamboo"
    ports:
      - "8085:8085"
      - "54663:54663"
    depends_on:
      - postgresql
    stdin_open: true
    tty: true
    entrypoint: /bin/sh
    labels:
      com.ragedunicorn.bamboo.environment: "dev"
      com.ragedunicorn.bamboo.description: "Bamboo container"
  postgresql:
    image: ragedunicorn/postgresql:${POSTGRESQL_TAG_VERSION}-dev
    volumes:
      - postgresql_data:/var/lib/postgresql/data
    environment:
      POSTGRESQL_APP_USER: "app"
      POSTGRESQL_APP_PASSWORD: "app"
    ports:
      - "5432:5432"
    stdin_open: true
    tty: true
    entrypoint: /bin/sh
    labels:
      com.ragedunicorn.postgresql.environment: "dev"
      com.ragedunicorn.postgresql.description: "PostgreSQL"
volumes:
  bamboo_data: {}
  bamboo_logs: {}
  postgresql_data: {}
