version: '3.6'
services:
  bamboo:
    build: .
    image: ragedunicorn/bamboo:1.0.0-dev
    volumes:
      - bamboo_data:/var/atlassian/bamboo
      - bamboo_logs:/opt/atlassian/bamboo/logs
    ports:
      - "8085:8085"
      - "54663:54663"
    stdin_open: true
    tty: true
    entrypoint: /bin/sh
    labels:
      com.ragedunicorn.bamboo.environment: "dev"
      com.ragedunicorn.bamboo.description: "Bamboo container"
volumes:
  bamboo_data: {}
  bamboo_logs: {}
