version: '3.7'
services:
  bamboo:
    build: .
    image: ragedunicorn/bamboo:${BAMBOO_TAG_VERSION}-stable
    volumes:
      - bamboo_data:/var/atlassian/bamboo
      - bamboo_logs:/opt/atlassian/bamboo/logs
    environment:
      POSTGRESQL_APP_USER: "app"
      POSTGRESQL_APP_PASSWORD: "app"
      POSTGRESQL_DATABASE_HOSTNAME: "postgresql"
      BAMBOO_DATABASE_NAME: "bamboo"
    ports:
      - "8085:8085"
    expose:
      - "54663"
    depends_on:
      - postgresql
    healthcheck:
      test: ["CMD", "/docker-healthcheck.sh"]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 1m
    labels:
      com.ragedunicorn.bamboo.environment: "prod"
      com.ragedunicorn.bamboo.description: "Bamboo container"
  postgresql:
    image: ragedunicorn/postgresql:${POSTGRESQL_TAG_VERSION}-stable
    volumes:
      - postgresql_data:/var/lib/postgresql
    environment:
      POSTGRESQL_APP_USER: "app"
      POSTGRESQL_APP_PASSWORD: "app"
    expose:
      - "5432"
    healthcheck:
      test: ["CMD", "/docker-healthcheck.sh"]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 1m
    labels:
      com.ragedunicorn.postgresql.environment: "prod"
      com.ragedunicorn.postgresql.description: "PostgreSQL"
volumes:
  bamboo_data: {}
  bamboo_logs: {}
  postgresql_data: {}
